name: sleek_circular_slider
description: A highly customizable circular slider/progress bar & spinner for Flutter.
version: 3.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: